# Generated by Django 2.1.4 on 2019-01-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sensor_id', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('sensorreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.SensorReading')),
                ('roll_PM25', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_PM25', models.DecimalField(decimal_places=2, max_digits=5)),
                ('site', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('bldgarea_c', models.CharField(max_length=100)),
                ('traffic_cl', models.CharField(max_length=100)),
            ],
            bases=('map.sensorreading',),
        ),
        migrations.CreateModel(
            name='MotionSensorReading',
            fields=[
                ('sensorreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.SensorReading')),
            ],
            bases=('map.sensorreading',),
        ),
        migrations.CreateModel(
            name='SoundLevelReading',
            fields=[
                ('sensorreading_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='map.SensorReading')),
                ('db_avg', models.FloatField()),
                ('db_min', models.FloatField()),
                ('db_max', models.FloatField()),
                ('db_l10', models.FloatField()),
                ('db_l50', models.FloatField()),
                ('db_l90', models.FloatField()),
            ],
            bases=('map.sensorreading',),
        ),
    ]
