# Generated by Django 2.1.5 on 2019-01-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airqualityreading',
            name='sensorreading_ptr',
        ),
        migrations.RemoveField(
            model_name='motionsensorreading',
            name='sensorreading_ptr',
        ),
        migrations.RemoveField(
            model_name='soundlevelreading',
            name='sensorreading_ptr',
        ),
        migrations.DeleteModel(
            name='AirQualityReading',
        ),
        migrations.DeleteModel(
            name='MotionSensorReading',
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
        migrations.DeleteModel(
            name='SoundLevelReading',
        ),
    ]
