# Generated by Django 2.1.5 on 2019-01-30 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('roll_PM25', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_PM25', models.DecimalField(decimal_places=2, max_digits=5)),
                ('site', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('bldgarea_c', models.CharField(max_length=100)),
                ('traffic_cl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotionReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('sensor_type', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('latest_reading', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SoundReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='motionreading',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sensor'),
        ),
        migrations.AddField(
            model_name='airqualityreading',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sensor'),
        ),
    ]
