# Generated by Django 2.1.5 on 2019-01-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airqualityreading',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='motionreading',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='soundreading',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
