# Generated by Django 2.1.5 on 2019-01-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190130_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityreading',
            name='current_PM25',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityreading',
            name='roll_PM25',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
