# Generated by Django 2.1.5 on 2019-01-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190130_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
