# Generated by Django 2.1.5 on 2019-02-02 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190130_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityreading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='api.Sensor'),
        ),
    ]
