# Generated by Django 2.1.5 on 2019-02-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190204_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundreading',
            name='d_l10',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundreading',
            name='d_l50',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundreading',
            name='d_l90',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundreading',
            name='davg',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundreading',
            name='dmax',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundreading',
            name='dmin',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
