# Generated by Django 2.1.5 on 2019-06-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190208_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sensor',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
