# Generated by Django 2.1.5 on 2019-08-05 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190627_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('count', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_readings', to='api.Sensor')),
            ],
        ),
    ]
