# Generated by Django 2.1.5 on 2019-08-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sensor_data_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
