# Generated by Django 2.1.5 on 2019-09-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sensor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedCountReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedcount_readings', to='api.Sensor')),
            ],
        ),
        migrations.RemoveField(
            model_name='motionreading',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='MotionReading',
        ),
    ]
