# Generated by Django 2.1.5 on 2019-09-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190912_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedcountreading',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
