# Generated by Django 2.1.5 on 2019-09-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190917_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedcountreading',
            old_name='value',
            new_name='count',
        ),
    ]
