# Generated by Django 2.1.5 on 2019-09-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190917_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='external_id',
            field=models.IntegerField(),
        ),
    ]
