# Generated by Django 2.1.5 on 2019-10-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190917_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedcountreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='soundreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trafficreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
