# Generated by Django 2.1.5 on 2019-10-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191002_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
